In [ ]:
H1 TITLE 
H2 TITLE

In [5]:
print("Buy the dip?")

Buy the dip?


In [19]:
import numpy as np
your_np_array=np.array([1,2.2,"Hallo",{"name":"Kevo"},{"Rex"},("Ow","oww"),[1],True], dtype=object)
for i in your_np_array:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'set'>
<class 'tuple'>
<class 'list'>
<class 'bool'>


In [4]:


# Create an array of 300 zeros
arr = np.zeros(300)

# Reshape it to (3, 100)
reshaped_arr = arr.reshape(3, 100)

print(reshaped_arr)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]]


In [5]:

# Create a 1D array with integers from 1 to 100
arr = np.arange(1, 101)

print(arr)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [3]:

# Select only odd numbers
odd_arr = arr[arr % 2 != 0]

print(odd_arr)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [7]:


# Select only even numbers
even_arr = arr[arr % 2 == 0][::-1]

print(even_arr)


[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


In [8]:
# Set every 3rd element starting from index 1 to 0
arr[1::3] = 0

print(arr)

[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72
  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90
  91   0  93  94   0  96  97   0  99 100]


In [18]:
# 1. Set the seed to 888 for reproducibility
np.random.seed(888)

# 2. Generate a 1D array of size 100 with a normal distribution
#    (mean = 0, std = 1 by default with np.random.randn)
normal_array = np.random.randn(100)

# 3. Generate a 2D array (8x8) with random integers from 1 to 10 (inclusive)
uniform_2d_array = np.random.randint(1, 11, size=(8, 8))  # upper bound is exclusive

# 4. Generate a 3D array (4x2x5) with random integers from 1 to 17 (inclusive)
uniform_3d_array = np.random.randint(1, 18, size=(4, 2, 5))

# Print outputs
print("1D Normal Distribution Array (100 elements):\n", normal_array)
print("\n2D Uniform Integer Array (8x8):\n", uniform_2d_array)
print("\n3D Uniform Integer Array (4x2x5):\n", uniform_3d_array)


1D Normal Distribution Array (100 elements):
 [-1.76200874e-01  1.88876361e-01  8.26747180e-01 -3.24473146e-02
 -6.52499418e-01 -1.05339382e-01  2.17776116e-01  5.87281504e-01
  1.00237892e-01 -1.09994668e+00 -2.55305389e-01  4.05304381e-01
  1.62663953e-01  1.04163462e+00  2.24324184e-01  6.99304449e-01
 -8.65543512e-01 -1.39346831e+00 -2.36687913e-01 -7.57041911e-01
  1.31429195e+00 -9.77385899e-01 -3.59032576e-01  1.16141585e-01
 -3.51081138e-01 -4.39838344e-01 -4.90995473e-02 -4.31596770e-01
 -1.08875099e+00 -2.31088106e+00 -1.86236420e+00  2.34708674e-01
 -8.95585921e-01 -5.40834525e-01 -4.02399061e-01  2.31458561e-02
  1.77688506e-01 -5.73309272e-01 -3.38392138e-01 -2.64422114e-03
  1.44930339e+00  1.36605641e+00  2.69187461e+00  6.76065035e-01
 -1.06098418e+00  1.31845313e-01  1.71934297e-01  8.88062794e-02
  1.03963016e+00 -1.37846942e-01 -3.69232844e-01  3.19587912e+00
  1.11457451e+00 -2.59516296e-01  1.48370897e+00 -1.57049065e+00
  9.78899330e-01  1.76070681e+00  3.53121953

In [24]:
arr_to_50=np.arange(1,51)
arr_51=np.arange(51,101)
conc=np.concatenate((arr_to_50,arr_51))
print(conc)
# Reshape into 10 rows and 10 columns
reshaped = conc.reshape((10, 10))
print(reshaped)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
