In [2]:
#Exercise 1
import numpy as np
from sklearn.impute import SimpleImputer


train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]            

train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]

imputer = SimpleImputer(strategy='mean')
imputer.fit(train_data)
print(imputer.statistics_)



[ 4. 13.  6.]


In [3]:
train_data_filled = imputer.transform(train_data)
print(train_data_filled)

[[ 7.  6.  5.]
 [ 4. 13.  5.]
 [ 1. 20.  8.]]


In [4]:
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]

test_data_filled = imputer.transform(test_data)
print(test_data_filled)


[[ 4.  1.  2.]
 [ 7. 13.  9.]
 [ 4.  2.  4.]]


In [5]:
#Exercise 2
from sklearn.preprocessing import StandardScaler

X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
print('Scaled', X_train_scaled)
print('Scaled mean',scaler.mean_)
print('Scaled std',scaler.scale_)



Scaled [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
Scaled mean [1.         0.         0.33333333]
Scaled std [0.81649658 0.81649658 1.24721913]


In [6]:
X_test = np.array([[ 2., -1.,  1.],
                   [ 3.,  3., -1.],
                   [ 1.,  1.,  1.]])

X_test_scaled = scaler.transform(X_test)
print("Scaled X_test:\n", X_test_scaled)


Scaled X_test:
 [[ 1.22474487 -1.22474487  0.53452248]
 [ 2.44948974  3.67423461 -1.06904497]
 [ 0.          1.22474487  0.53452248]]


In [8]:
#Exercise 3
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

X_train = [['Python'], ['Java'], ['Java'], ['C++']]

encoder = OneHotEncoder(handle_unknown='ignore')
X_train_encoded = encoder.fit_transform(X_train).toarray()
df = pd.DataFrame(X_train_encoded, columns=encoder.get_feature_names_out())
print(df)



   x0_C++  x0_Java  x0_Python
0     0.0      0.0        1.0
1     0.0      1.0        0.0
2     0.0      1.0        0.0
3     1.0      0.0        0.0


In [9]:
X_test = [['Python'], ['Java'], ['C'], ['C++']]
X_test_encoded = encoder.transform(X_test).toarray()
df_test = pd.DataFrame(X_test_encoded, columns=encoder.get_feature_names_out())
print(df_test)

   x0_C++  x0_Java  x0_Python
0     0.0      0.0        1.0
1     0.0      1.0        0.0
2     0.0      0.0        0.0
3     1.0      0.0        0.0


In [10]:
#Exercise 4
from sklearn.preprocessing import OrdinalEncoder

X_train = [['good'], ['bad'], ['neutral']]

encoder = OrdinalEncoder(categories=[['bad', 'neutral', 'good']])
X_train_encoded = encoder.fit_transform(X_train)
print("Encoded X_train:\n", X_train_encoded)
print("Categories:", encoder.categories_)



Encoded X_train:
 [[2.]
 [0.]
 [1.]]
Categories: [array(['bad', 'neutral', 'good'], dtype=object)]
