In [2]:
#Exercise 1
import numpy as np
from sklearn.impute import SimpleImputer


train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]            

train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]

imputer = SimpleImputer(strategy='mean')
imputer.fit(train_data)
print(imputer.statistics_)



[ 4. 13.  6.]


In [3]:
train_data_filled = imputer.transform(train_data)
print(train_data_filled)

[[ 7.  6.  5.]
 [ 4. 13.  5.]
 [ 1. 20.  8.]]


In [4]:
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]

test_data_filled = imputer.transform(test_data)
print(test_data_filled)


[[ 4.  1.  2.]
 [ 7. 13.  9.]
 [ 4.  2.  4.]]


In [5]:
#Exercise 2
from sklearn.preprocessing import StandardScaler

X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
print('Scaled', X_train_scaled)
print('Scaled mean',scaler.mean_)
print('Scaled std',scaler.scale_)



Scaled [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
Scaled mean [1.         0.         0.33333333]
Scaled std [0.81649658 0.81649658 1.24721913]


In [6]:
X_test = np.array([[ 2., -1.,  1.],
                   [ 3.,  3., -1.],
                   [ 1.,  1.,  1.]])

X_test_scaled = scaler.transform(X_test)
print("Scaled X_test:\n", X_test_scaled)


Scaled X_test:
 [[ 1.22474487 -1.22474487  0.53452248]
 [ 2.44948974  3.67423461 -1.06904497]
 [ 0.          1.22474487  0.53452248]]


In [8]:
#Exercise 3
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

X_train = [['Python'], ['Java'], ['Java'], ['C++']]

encoder = OneHotEncoder(handle_unknown='ignore')
X_train_encoded = encoder.fit_transform(X_train).toarray()
df = pd.DataFrame(X_train_encoded, columns=encoder.get_feature_names_out())
print(df)



   x0_C++  x0_Java  x0_Python
0     0.0      0.0        1.0
1     0.0      1.0        0.0
2     0.0      1.0        0.0
3     1.0      0.0        0.0


In [9]:
X_test = [['Python'], ['Java'], ['C'], ['C++']]
X_test_encoded = encoder.transform(X_test).toarray()
df_test = pd.DataFrame(X_test_encoded, columns=encoder.get_feature_names_out())
print(df_test)

   x0_C++  x0_Java  x0_Python
0     0.0      0.0        1.0
1     0.0      1.0        0.0
2     0.0      0.0        0.0
3     1.0      0.0        0.0


In [10]:
#Exercise 4
from sklearn.preprocessing import OrdinalEncoder

X_train = [['good'], ['bad'], ['neutral']]

encoder = OrdinalEncoder(categories=[['bad', 'neutral', 'good']])
X_train_encoded = encoder.fit_transform(X_train)
print("Encoded X_train:\n", X_train_encoded)
print("Categories:", encoder.categories_)



Encoded X_train:
 [[2.]
 [0.]
 [1.]]
Categories: [array(['bad', 'neutral', 'good'], dtype=object)]


In [11]:
X_test = [['good'], ['good'], ['bad']]
X_test_encoded = encoder.transform(X_test)
print("Encoded X_test:\n", X_test_encoded)

Encoded X_test:
 [[2.]
 [2.]
 [0.]]


In [12]:
#Exercise 5
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer

# Load data (assuming file path)
df = pd.read_csv('breast-cancer.csv', header=None, names=['age', 'menopause', 'tumor-size', 'inv-nodes', 'node-caps', 'deg-malig', 'breast', 'breast-quad', 'irradiat', 'Class'])
print(df.columns)
df = df.drop('Class', axis=1).dropna()
X_train, X_test = train_test_split(df, test_size=0.2, random_state=43)



Index(['age', 'menopause', 'tumor-size', 'inv-nodes', 'node-caps', 'deg-malig',
       'breast', 'breast-quad', 'irradiat', 'Class'],
      dtype='object')


In [13]:
print(X_train.nunique())

age             6
menopause       3
tumor-size     11
inv-nodes       6
node-caps       2
deg-malig       3
breast          2
breast-quad     5
irradiat        2
dtype: int64


In [14]:
ohe_cols = ['node-caps', 'breast', 'breast-quad', 'irradiat']
ohe = OneHotEncoder(handle_unknown='ignore')
X_train_ohe = ohe.fit_transform(X_train[ohe_cols])
X_test_ohe = ohe.transform(X_test[ohe_cols]).toarray()
print("OHE features:", ohe.get_feature_names_out(ohe_cols))
print(X_test_ohe[:10])

OHE features: ['node-caps_no' 'node-caps_yes' 'breast_left' 'breast_right'
 'breast-quad_central' 'breast-quad_left_low' 'breast-quad_left_up'
 'breast-quad_right_low' 'breast-quad_right_up' 'irradiat_no'
 'irradiat_yes']
[[1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.]]


In [15]:
ordinal_cols = ["menopause", "age", "tumor-size", "inv-nodes", "deg-malig"]
categories = [
    ['lt40', 'premeno', 'ge40'],
    ['10-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80-89', '90-99'],
    ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59'],
    ['0-2', '3-5', '6-8', '9-11', '12-14', '15-17', '18-20', '21-23', '24-26', '27-29', '30-32', '33-35', '36-39'],
    [1, 2, 3]
]
oe = OrdinalEncoder(categories=categories)
X_train_oe = oe.fit_transform(X_train[ordinal_cols])
X_test_oe = oe.transform(X_test[ordinal_cols])
print(X_test_oe[:10])

[[2. 5. 2. 0. 1.]
 [2. 5. 2. 0. 0.]
 [2. 5. 4. 5. 2.]
 [1. 4. 5. 1. 1.]
 [2. 5. 5. 0. 2.]
 [1. 2. 1. 0. 1.]
 [1. 2. 8. 0. 1.]
 [2. 5. 2. 0. 0.]
 [2. 5. 5. 0. 2.]
 [1. 2. 3. 0. 0.]]


In [16]:
preprocessor = make_column_transformer(
    (ohe, ohe_cols),
    (oe, ordinal_cols)
)
X_train_combined = preprocessor.fit_transform(X_train)
X_test_combined = preprocessor.transform(X_test)
print(X_test_combined[:2])

[[1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 2. 5. 2. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 2. 5. 2. 0. 0.]]
